### ISSUE TITLE
Source of battery model function

### ISSUE THREAD

**Issue by sathoshik** [christiansiegel/electrical-circuit-battery-model#1]
Do you recall the reference for the Transient_S, CTransient_S, RTransient_L, and CTransient_L functions? The function seems to be different from the _Accurate electrical battery model capable of predicting runtime and I-V performance_ paper you cited. 

https://github.com/christiansiegel/electrical-circuit-battery-model/blob/ea9783e280b06ee676ceb312571a0236a5619249/batteries.py#L51-L56

**Comment by christiansiegel** [comment]
I think I used higher order functions. See "2.3 Parameter Extraction" for details.

**Comment by sathoshik** [comment]
Did you mean model extraction? These functions are different from the ones you have listed. Just curious to where you got the higher order function. 

Cheers,

<img width="663" alt="Screen Shot 2019-06-24 at 9 35 50 AM" src="https://user-images.githubusercontent.com/20143225/60023280-7f1c4a80-9663-11e9-9578-b9a7f66cc5c8.png">

**Comment by christiansiegel** [comment]
Ah, sorry. I see what you mean. There is no reference for them. I just used those because I could fit them closer to my physical measurements.
